[package]
name = "spellbook"
version = "1.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
peekmore = "1.0.0"
lazy_static = "1.4.0"
maplit = "1.0.2"
